//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booksCrudApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public string id { get; set; }
        public string name { get; set; }
        public int numberOfPages { get; set; }
        public string dateOfPublication { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string authors { get; set; }
        public int isDeleted { get; set; }
    }
}
